Spring:
  datasource:
    url: jdbc:h2:~/data/data
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012
---
Spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
